name = "hit-counter-worker"
main = "src/worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
env.dev = { vars = { API_BASE = "http://localhost:8787" } }

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "HIT_COUNTER_KV"
id = "4cb8e06d1d82414f9878ddffb67f9888"
preview_id = "hit-counter-preview"

[env.production]
kv_namespaces = [
    { binding = "HIT_COUNTER_KV", id = "4cb8e06d1d82414f9878ddffb67f9888" }
]